from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

BACKEND_ROOT = Path(__file__).resolve().parents[2]
ENV_FILE = BACKEND_ROOT / ".env"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=ENV_FILE,
        env_file_encoding="utf-8",
    )

    app_name: str = "Project AI Clipper API"
    cors_origins: list[str] = ["http://localhost:3000"]
    upload_dir: Path = BACKEND_ROOT / "uploads"
    processed_dir: Path = BACKEND_ROOT / "processed"
    audio_dir: Path = BACKEND_ROOT / "audio"
    transcripts_dir: Path = BACKEND_ROOT / "transcripts"
    max_upload_size_bytes: int = 5 * 1024 * 1024 * 1024  # 5 GB
    allowed_extensions: set[str] = {".mp4", ".mov", ".mkv", ".webm"}
    chunk_size_bytes: int = 1024 * 1024  # 1 MB
    project_metadata_filename: str = "project.json"
    ffprobe_timeout_seconds: int = 120
    ffmpeg_timeout_seconds: int = 600
    audio_output_filename: str = "audio.wav"
    transcript_output_filename: str = "transcript.json"
    whisper_model_size: str = "base"
    whisper_device: str = "auto"
    whisper_compute_type: str = "int8"
    transcription_default_quality_mode: str = "balanced"
    transcription_clip_boundary_padding_seconds: float = 0.75
    transcription_temp_dir_name: str = "_transcribe_temp"
    transcription_max_recovery_coverage_ratio: float = 0.15
    transcription_recovery_merge_gap_seconds: float = 0.5
    transcription_early_exit_min_coverage: float = 0.82
    transcription_early_exit_max_gap_seconds: float = 2.5
    transcription_early_exit_min_avg_confidence: float = 0.58
    enable_transcription_diagnostics: bool = True
    analysis_dir: Path = BACKEND_ROOT / "analysis"
    analysis_output_filename: str = "analysis.json"
    analysis_provider: str = "auto"
    analysis_external_provider: str = "openai"
    analysis_model: str = "gpt-4o-mini"
    analysis_api_key: str = ""
    analysis_api_base_url: str | None = None
    analysis_batch_size: int = 10
    analysis_timeout_seconds: int = 120
    analysis_max_transcript_chars: int = 12000
    analysis_context_segments: int = 2
    analysis_max_retries: int = 2
    analysis_long_video_threshold_seconds: float = 1800.0
    analysis_window_seconds: float = 900.0
    analysis_window_overlap_seconds: float = 120.0
    analysis_semantic_window_seconds: float = 180.0
    analysis_semantic_window_overlap_seconds: float = 30.0
    analysis_min_window_speech_seconds: float = 20.0
    analysis_max_deep_windows: int = 4
    analysis_max_model_requests: int = 8
    analysis_deep_worker_count: int = 2
    analysis_total_timeout_seconds: float = 120.0
    analysis_window_timeout_seconds: float = 30.0
    analysis_pipeline_version: str = "2"
    clip_candidates_dir: Path = BACKEND_ROOT / "clip_candidates"
    clip_candidates_output_filename: str = "clip_candidates.json"
    clip_selection_min_duration_seconds: float = 15.0
    clip_selection_preferred_min_duration_seconds: float = 15.0
    clip_selection_preferred_max_duration_seconds: float = 45.0
    clip_selection_max_duration_seconds: float = 120.0
    clip_selection_short_min_seconds: float = 15.0
    clip_selection_short_max_seconds: float = 30.0
    clip_selection_medium_min_seconds: float = 30.0
    clip_selection_medium_max_seconds: float = 60.0
    clip_selection_long_min_seconds: float = 60.0
    clip_selection_long_max_seconds: float = 120.0
    clip_selection_max_candidates_before_ranking: int = 30
    clip_selection_max_candidates_per_window: int = 6
    clip_selection_context_padding_seconds: float = 3.0
    clip_selection_max_gap_seconds: float = 2.5
    clip_selection_max_candidates: int = 8
    clip_selection_hard_max_candidates: int = 10
    clip_selection_max_seed_groups: int = 12
    clip_selection_opening_coverage_seconds: float = 60.0
    clip_selection_early_coverage_fraction: float = 0.15
    clip_selection_additional_clip_min_margin: float = 3.0
    clip_selection_min_score: float = 40.0
    clip_selection_quality_threshold: float = 52.0
    clip_selection_post_payoff_tail_min_seconds: float = 1.0
    clip_selection_post_payoff_tail_max_seconds: float = 6.5
    clip_selection_lead_in_max_seconds: float = 4.0
    clip_selection_pipeline_version: str = "6"
    clip_selection_preferred_target_max_seconds: float = 30.0
    visual_analysis_dir: Path = BACKEND_ROOT / "visual_analysis"
    visual_analysis_output_filename: str = "visual_analysis.json"
    visual_analysis_pipeline_version: str = "1"
    visual_analysis_enabled: bool = True
    visual_analysis_sample_interval_seconds: float = 3.0
    visual_analysis_target_samples_per_minute: float = 20.0
    visual_analysis_window_seconds: float = 4.0
    visual_analysis_scene_change_threshold: float = 0.18
    visual_analysis_motion_spike_threshold: float = 0.22
    visual_analysis_frame_width: int = 160
    visual_analysis_frame_height: int = 90
    visual_analysis_ranking_mode: str = "conservative"
    visual_analysis_max_visual_boost: float = 2.5
    visual_analysis_exceptional_visual_boost: float = 3.0
    visual_analysis_exceptional_motion_threshold: float = 8.5
    visual_analysis_min_transcript_score_for_boost: float = 52.0
    visual_analysis_tie_breaker_max_boost: float = 1.5
    visual_analysis_alignment_window_seconds: float = 1.0
    visual_analysis_payoff_alignment_window_seconds: float = 0.8
    visual_analysis_visual_boundary_max_extension_seconds: float = 2.0
    clip_selection_narrative_arc_score_margin: float = 5.0
    clip_export_min_duration_seconds: float = 15.0
    clip_export_max_duration_seconds: float = 120.0
    clip_export_subdir: str = "clips"
    clip_captions_subdir: str = "captions"
    clip_exports_manifest_filename: str = "exports.json"
    clip_export_timeout_seconds: int = 600
    caption_presets_subdir: str = "caption_presets"
    caption_presets_store_filename: str = "custom_presets.json"
    expose_detailed_render_errors: bool = True
    caption_ass_debug_logging: bool = True
    log_level: str = "INFO"
    discovery_transcript_output_filename: str = "discovery_transcript.json"
    discovery_chunk_state_filename: str = "chunk_state.json"
    discovery_chunks_subdir: str = "discovery_chunks"
    clip_transcripts_subdir: str = "clip_transcripts"
    discovery_chunk_seconds: float = 1200.0
    discovery_chunk_overlap_seconds: float = 10.0
    discovery_worker_count: int = 1
    discovery_condition_on_previous_text: bool = False
    discovery_short_video_chunk_threshold_seconds: float = 1200.0
    discovery_persist_chunk_transcripts: bool = False
    discovery_persist_chunk_state: bool = True
    clip_retranscription_padding_seconds: float = 3.0
    clip_retranscription_quality_mode: str = "balanced"
    automated_pipeline_enabled: bool = True


settings = Settings()
